version: '3.8'

services:
    deptrac:
        build:
            dockerfile: docker/php/Dockerfile
            context: ./
        container_name: deptrac
        tty: true
        user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
        working_dir: /var/www/deptrac
        volumes:
            - ./:/var/www/deptrac
        extra_hosts:
            - host.docker.internal:${HOST_IP:-172.17.0.1}

